name: think-generator CI
on: [push, pull_request]
jobs:
    pipeline:
        name: think-generator pipeline
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]')"
        timeout-minutes: 40
        env:
            SPRING_OUTPUT_ANSI_ENABLED: DETECT
            SPRING_JPA_SHOW_SQL: false
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-java@v1
              with:
                  java-version: 1.8
                  server-id: sonatype-nexus-snapshots
                  server-username: MAVEN_USERNAME
                  server-password: MAVEN_PASSWORD
            - name: Run backend test
              run: |
                  chmod +x mvnw
                  ./mvnw -ntp clean
#            - name: Analyze code with SonarQube
#              env:
#                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#              run: |
#                  if [ -n $SONAR_TOKEN ]; then
#                      ./mvnw -ntp initialize sonar:sonar -Dsonar.host.url=https://sonarcloud.io
#                  else
#                      echo No SONAR_TOKEN, skipping...
#                  fi
            - name: Package application
              run: ./mvnw -ntp package deploy -DskipTests -DaltReleaseDeploymentRepository=sonatype-nexus-staging::default::https://oss.sonatype.org/service/local/staging/deploy/maven2/ -DaltSnapshotDeploymentRepository=sonatype-nexus-snapshots::default::https://oss.sonatype.org/content/repositories/snapshots/
              env:
                  MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
                  MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
#            - uses: actions/upload-artifact@v2
#              with:
#                name: dist
#                path: target
